Mac: remove 32-bit Mac from build
Remove 32-bit Mac from build; includes removing a few 32-bit Mac-only camera libs

diff --git a/run_cmake-osx b/run_cmake-osx
--- a/run_cmake-osx
+++ b/run_cmake-osx
@@ -2,7 +2,7 @@
 
 here=$(cd $(dirname "$0"); /bin/pwd)
 
-# usage: run_cmake-osx [-g] 32|64
+# usage: run_cmake-osx [-g]
 
 tmp=tmp
 buildtype=Release
@@ -13,15 +13,18 @@ if [[ $1 = -g ]]; then
     shift
 fi
 
-case $1 in
-    32)   APPLE_ARCH=i386 ; shift ;;
-    64)   APPLE_ARCH=x86_64 ; shift ;;
-    *)    echo "usage: $0 32|64" >&2; exit 1 ;;
-esac
+os=$(IFS=. read -r a b _ < <(sysctl -n kern.osproductversion); printf "%03d" "$a" "$b")
+sonoma=014000
+cmake_extra_args=()
+if [[ $os > $sonoma || $os == $sonoma ]]; then
+    cmake_extra_args+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=14.0)
+fi
+
+APPLE_ARCH=x86_64
 
 WXWIN=$(wx-config --prefix)
 [[ -d $WXWIN ]] || {
-    echo "could not find wxWidgets insalltation" >&2
+    echo "could not find wxWidgets installation" >&2
     exit 1
 }
 
@@ -35,4 +38,6 @@ cmake -G "Unix Makefiles" \
     -DwxWidgets_PREFIX_DIRECTORY="$WXWIN" \
     -DAPPLE_ARCH="$APPLE_ARCH" \
     -DCMAKE_BUILD_TYPE="$buildtype" \
-    "$@" ..
+    "${cmake_extra_args[@]}" \
+    "$@" \
+    ..
